export const todosTypes = {
    FETCH_TODOS_PENDING: 'FETCH_TODOS_PENDING',
    FETCH_TODOS_FULFILLED: 'FETCH_TODOS_FULFILLED',
    FETCH_TODOS_REJECTED: 'FETCH_TODOS_REJECTED',
    NEW_TODO: 'NEW_TODO',
    SAVE_TODO: 'SAVE_TODO',
    FETCH_TODOS_BY_ID_PENDING: 'FETCH_TODOS_BY_ID_PENDING',
    FETCH_TODOS_BY_ID_FULFILLED: 'FETCH_TODOS_BY_ID_FULFILLED',
    FETCH_TODOS_BY_ID_REJECTED: 'FETCH_TODOS_BY_ID_REJECTED',
    UPDATE_TODO: 'UPDATE_TODO',
    DELETE_TODO: 'DELETE_TODO'
};

export const productosTypes = {
    FETCH_PRODUCTOS_PENDING: 'FETCH_PRODUCTOS_PENDING',
    FETCH_PRODUCTOS_FULFILLED: 'FETCH_PRODUCTOS_FULFILLED',
    FETCH_PRODUCTOS_REJECTED: 'FETCH_PRODUCTOS_REJECTED',
    NEW_PRODUCTO: 'NEW_PRODUCTO',
    SAVE_PRODUCTO: 'SAVE_PRODUCTO',
    FETCH_PRODUCTOS_BY_ID_PENDING: 'FETCH_PRODUCTOS_BY_ID_PENDING',
    FETCH_PRODUCTOS_BY_ID_FULFILLED: 'FETCH_PRODUCTOS_BY_ID_FULFILLED',
    FETCH_PRODUCTOS_BY_ID_REJECTED: 'FETCH_PRODUCTOS_BY_ID_REJECTED',
    UPDATE_PRODUCTO: 'UPDATE_PRODUCTO',
    DELETE_PRODUCTO: 'DELETE_PRODUCTO'
};

export const serviciosTypes = {   //arreglar los nombres!!! ->> OK!!
FETCH_SERVICIOS_PENDING: 'FETCH_SERVICIOS_PENDING',
FETCH_SERVICIOS_FULFILLED: 'FETCH_SERVICIOS_FULFILLED',
FETCH_SERVICIOS_REJECTED: 'FETCH_SERVICIOS_REJECTED',
NEW_SERVICIO: 'NEW_SERVICIO',
SAVE_SERVICIO: 'SAVE_SERVICIO',
FETCH_SERVICIOS_BY_ID_PENDING: 'FETCH_SERVICIOS_BY_ID_PENDING',
FETCH_SERVICIOS_BY_ID_FULFILLED: 'FETCH_SERVICIOS_BY_ID_FULFILLED',
FETCH_SERVICIOS_BY_ID_REJECTED: 'FETCH_SERVICIOS_BY_ID_REJECTED',
UPDATE_SERVICIO: 'UPDATE_SERVICIO',
DELETE_SERVICIO: 'DELETE_SERVICIO'
};

export const contactosTypes = {
    NEW_CONTACTO: 'NEW_CONTACTO',
    SAVE_CONTACTO: 'SAVE_CONTACTO',
    
};

export const usuariosTypes = {
    NEW_USUARIO: 'NEW_USUARIO',
    SAVE_USUARIO: 'SAVE_USUARIO',
    
};


export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
