export const todosTypes = {
    FETCH_TODOS_PENDING: 'FETCH_TODOS_PENDING',
    FETCH_TODOS_FULFILLED: 'FETCH_TODOS_FULFILLED',
    FETCH_TODOS_REJECTED: 'FETCH_TODOS_REJECTED',
    NEW_TODO: 'NEW_TODO',
    SAVE_TODO: 'SAVE_TODO',
    FETCH_TODOS_BY_ID_PENDING: 'FETCH_TODOS_BY_ID_PENDING',
    FETCH_TODOS_BY_ID_FULFILLED: 'FETCH_TODOS_BY_ID_FULFILLED',
    FETCH_TODOS_BY_ID_REJECTED: 'FETCH_TODOS_BY_ID_REJECTED',
    UPDATE_TODO: 'UPDATE_TODO',
    DELETE_TODO: 'DELETE_TODO'
};

export const productosTypes = {
    FETCH_PRODUCTOS_PENDING: 'FETCH_PRODUCTOS_PENDING',
    FETCH_PRODUCTOS_FULFILLED: 'FETCH_PRODUCTOS_FULFILLED',
    FETCH_PRODUCTOS_REJECTED: 'FETCH_PRODUCTOS_REJECTED',
    NEW_PRODUCTO: 'NEW_PRODUCTO',
    SAVE_PRODUCTO: 'SAVE_PRODUCTO',
    FETCH_PRODUCTOS_BY_ID_PENDING: 'FETCH_PRODUCTOS_BY_ID_PENDING',
    FETCH_PRODUCTOS_BY_ID_FULFILLED: 'FETCH_PRODUCTOS_BY_ID_FULFILLED',
    FETCH_PRODUCTOS_BY_ID_REJECTED: 'FETCH_PRODUCTOS_BY_ID_REJECTED',
    UPDATE_PRODUCTO: 'UPDATE_PRODUCTO',
    DELETE_PRODUCTO: 'DELETE_PRODUCTO'
};

export const serviciosTypes = {   //arreglar los nombres!!!
LISTA_SERVICIOS_PENDIENTE: 'lista_servicios_pendiente',
LISTA_SERVICIOS_CUMPLIDO: 'lista_servicios_cumplido',
LISTA_SERVICIOS_RECHAZADO: 'lista_servicios_rechazado',
NEW_SERVICIO:'new_servicio',
SAVE_SERVICIO:'save_servicio',
FETCH_SERVICIO_BY_ID_PENDIENTE:'fetch_servicio_by_id_pendiente',
FETCH_SERVICIO_BY_ID_CUMPLIDO:'fetch_servicio_by_id_cumplido',
FETCH_SERVICIO_BY_ID_RECHAZADO:"fetch_servicio_by_id_rechazado",
UPDATE_SERVICIO:'pdate_servicio',
DELETE_SERVICIO:'delete_servicio'
};
